### ISSUE TITLE
Add sgx support

### ISSUE THREAD

**Issue by sbellem** [initc3/libsodium#1]
Work in progress on [libsodium-sgx](https://github.com/initc3/libsodium/tree/libsodium-sgx) branch. This work is based on the pull request https://github.com/jedisct1/libsodium/pull/688.

**TODO**

- [ ] Test hardware mode: `./configure --enable-sgx-hw-tests`
- [ ] Test on a CI infrastructure. For the **simulation mode**, the existing `.travis.yml` can perhaps be adapted to run a job for the SGX tests. As for the **hardware mode**, I am not sure how. Using [drone.io](https://www.drone.io/)? Have a look at other projects, such as ring-sgx: https://github.com/mesalock-linux/ring-sgx/commit/844efe271ed78a399d803b2579f5f2424d543c9f#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7
- [ ] Add job to `.travis.yml` for tests with SGX in simulation mode.
- [ ] Upgrade to a more recent SGX version. Currently, the simulation mode tests pass with [linux-sgx](https://github.com/intel/linux-sgx) version 2.6, Ubuntu 16.04.
